name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies for frontend
      working-directory: frontend
      run: npm install

    - name: Run frontend tests
      working-directory: frontend
      run: npm test

    - name: Install dependencies for backend
      working-directory: backend
      run: npm install

    - name: Run backend tests
      working-directory: backend
      run: npm test

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v1.3
      with:
        projectKey: joaovitormsilva_GCMES-Trabalho2
        organization: joaovitormsilva
        token: ${{ secrets.SONAR_TOKEN }}
        options: >
          -Dsonar.sources=backend,frontend
          -Dsonar.tests=backend/tests,frontend/tests
          -Dsonar.inclusions=**/*.js
